camel.main.name=InboundProcessor
camel.management.port=8090
camel.component.mapstruct.mapper-package-name=com.ivan.inbound.mapper

camel.component.kafka.brokers={{env:KAFKA_BROKERS}}
camel.component.kafka.auto-offset-reset=earliest
camel.component.kafka.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
camel.component.kafka.additional-properties[schema.registry.url]={{env:SCHEMA_REGISTRY_URL}}

# Kafka Configuration
kafka.topic=diploma-orders-topic
kafka.dead-letter-topic=diploma-orders-topic-dlt

# Rest Configuration
camel.rest.port=8080
