camel.main.name=InboundProcessor
camel.component.mapstruct.mapper-package-name=com.ivan.inbound.mapper

# Kafka component configuration - using environment variable resolution
camel.component.kafka.brokers={{env:KAFKA_BROKERS:localhost:9092}}
camel.component.kafka.auto-offset-reset=earliest
camel.component.kafka.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#TODO: use Avro?

# Kafka Configuration - define properties that will be referenced with {{}} syntax
kafka.topic=topic-inbound-processor
kafka.dead-letter-topic=topic-inbound-processor-dlt

# Rest Configuration
camel.rest.port=8080
