camel.main.name=InboundProcessor
camel.component.mapstruct.mapper-package-name=com.ivan.inbound.mapper

camel.component.kafka.brokers=localhost:9092
camel.component.kafka.auto-offset-reset=earliest
camel.component.kafka.value-serializer = org.apache.kafka.common.serialization.StringSerializer
#TODO: use Avro?

# Kafka Configuration
kafka.topic=diploma-orders-topic
kafka.dead-letter-topic=diploma-orders-topic-dlt

# Rest Configuration
camel.rest.port=8080
