camel.main.name=OutboundProcessor
camel.component.mapstruct.mapper-package-name=com.ivan.outbound.mapper

camel.component.kafka.brokers=localhost:9092
camel.component.kafka.auto-offset-reset=earliest
#TODO: use Avro?

# Kafka Configuration TODO update topic name
kafka.topic=topic-inbound-processor
kafka.group-id=outbound-processor-group
kafka.dead-letter-topic=topic-inbound-processor-dlt