camel.main.name=OutboundProcessor
camel.main.main-listener-classes=com.ivan.outbound.listener.DatabaseSeedListener
camel.component.mapstruct.mapper-package-name=com.ivan.outbound.mapper

camel.component.kafka.brokers=localhost:9092
camel.component.kafka.auto-offset-reset=earliest
camel.component.kafka.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
camel.component.kafka.additional-properties[schema.registry.url]={{env:SCHEMA_REGISTRY_URL:http://localhost:8181}}
camel.component.kafka.additional-properties[specific.avro.reader]=true

# Kafka Configuration
kafka.topic=diploma-orders-topic
kafka.dead-letter-topic=diploma-orders-topic-dlt
kafka.group-id=outbound-processor-group-id

#TODO: implement currency api for mapping
api.currency.base-url=https://api.exchangerate-api.com

# Currency cache (TTL in hours — rates refresh daily so 1h is a safe default)
cache.currency.ttl-hours=1

