camel.main.name=OutboundProcessor
camel.component.mapstruct.mapper-package-name=com.ivan.outbound.mapper

camel.component.kafka.brokers={{env:KAFKA_BROKERS:localhost:9092}}
camel.component.kafka.auto-offset-reset=earliest
camel.component.kafka.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#TODO: use Avro?

# Kafka Configuration
kafka.topic={{env:KAFKA_TOPIC:topic-inbound-processor}}
kafka.dead-letter-topic={{env:KAFKA_DLT_TOPIC:topic-inbound-processor-dlt}}
kafka.group-id={{env:KAFKA_GROUP_ID:outbound-processor-group}}
