apiVersion: v1
kind: Service
metadata:
  name: inbound-processor
  namespace: diploma-app
  labels:
    app: inbound-processor
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
      protocol: TCP
  selector:
    app: inbound-processor

