apiVersion: v1
kind: Service
metadata:
  name: outbound-processor
  namespace: diploma-app
  labels:
    app: outbound-processor
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
      protocol: TCP
  selector:
    app: outbound-processor

